# Generated by Django 3.1.2 on 2020-10-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='status',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('disabled', 'Disabled')], default='unspecified', max_length=20),
        ),
    ]
