# Generated by Django 3.1.2 on 2020-10-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0003_ticker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
