# Generated by Django 3.1.2 on 2020-10-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0004_auto_20201025_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRequestCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('request_url', models.URLField(db_index=True)),
                ('response_blob', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
