# Generated by Django 3.1.2 on 2020-11-23 00:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0007_auto_20201116_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=200),
        ),
    ]
