# Generated by Django 3.1.2 on 2020-12-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0008_auto_20201122_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscriber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
