# Generated by Django 3.1.2 on 2020-12-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0012_auto_20201216_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('', 'Unknown'), ('INACTIVE', 'Inactive'), ('ACTIVE', 'Active')], default='', max_length=200, verbose_name='Subscription status'),
        ),
    ]
