# Generated by Django 3.1.2 on 2021-01-01 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0013_auto_20201225_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('is_long', models.BooleanField()),
                ('units', models.PositiveIntegerField()),
                ('cash', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('external_cache', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiger.externalrequestcache')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiger.ticker')),
            ],
            options={
                'unique_together': {('ticker', 'external_cache')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('unspecified', 'Unspecified'), ('long_call', 'Long call'), ('covered_call', 'Covered call'), ('long_put', 'Long put'), ('cash_secured_put', 'Cash secured put')], default='unspecified', max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('legs', models.ManyToManyField(to='tiger.Leg')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiger.stocksnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionContractSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('is_call', models.BooleanField()),
                ('strike', models.FloatField()),
                ('expiration_timestamp', models.PositiveIntegerField()),
                ('external_cache', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiger.externalrequestcache')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiger.ticker')),
            ],
            options={
                'unique_together': {('ticker', 'is_call', 'strike', 'expiration_timestamp', 'external_cache')},
            },
        ),
        migrations.AddField(
            model_name='leg',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiger.optioncontractsnapshot'),
        ),
        migrations.AddField(
            model_name='leg',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiger.stocksnapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='leg',
            unique_together={('is_long', 'units', 'cash', 'stock', 'contract')},
        ),
    ]
