# Generated by Django 3.1.2 on 2021-01-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0015_auto_20210101_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legsnapshot',
            old_name='cash',
            new_name='cash_snapshot',
        ),
        migrations.RenameField(
            model_name='legsnapshot',
            old_name='contract',
            new_name='contract_snapshot',
        ),
        migrations.RenameField(
            model_name='legsnapshot',
            old_name='stock',
            new_name='stock_snapshot',
        ),
        migrations.RenameField(
            model_name='tradesnapshot',
            old_name='legs',
            new_name='leg_snapshots',
        ),
        migrations.RenameField(
            model_name='tradesnapshot',
            old_name='stock',
            new_name='stock_snapshot',
        ),
        migrations.AlterUniqueTogether(
            name='legsnapshot',
            unique_together={('is_long', 'units', 'cash_snapshot', 'stock_snapshot', 'contract_snapshot')},
        ),
    ]
