# Generated by Django 3.1.2 on 2021-01-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0016_auto_20210101_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncontractsnapshot',
            name='premium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='legsnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='optioncontractsnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stocksnapshot',
            unique_together=set(),
        ),
    ]
