# Generated by Django 3.1.2 on 2021-01-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0017_auto_20210101_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legsnapshot',
            name='cash_snapshot',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
