# Generated by Django 3.1.2 on 2021-01-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0018_auto_20210104_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='legsnapshot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
