# Generated by Django 3.1.2 on 2021-01-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0019_legsnapshot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesnapshot',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
