# Generated by Django 3.1.2 on 2021-01-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    def replicate_target_prices(apps, _):
        TradeSnapshot = apps.get_model('tiger', 'TradeSnapshot')
        for trade_snapshot in TradeSnapshot.objects.all():
            if trade_snapshot.target_price_lower:
                trade_snapshot.target_price_upper = trade_snapshot.target_price_lower
                trade_snapshot.save()

    dependencies = [
        ('tiger', '0022_tradesnapshot_target_price_upper'),
    ]

    operations = [
        migrations.RunPython(replicate_target_prices),
    ]
