# Generated by Django 3.1.2 on 2021-01-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0023_auto_20210116_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legsnapshot',
            name='name',
        ),
    ]
