# Generated by Django 3.1.2 on 2021-02-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0025_auto_20210126_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesnapshot',
            name='premium_type',
            field=models.CharField(choices=[('mid', 'Mid/mark'), ('market', 'Market order')], default='mid', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradesnapshot',
            name='type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('long_call', 'Long call'), ('covered_call', 'Covered call'), ('long_put', 'Long put'), ('cash_secured_put', 'Cash secured put'), ('bull_call_spread', 'Bull call spread'), ('bear_call_spread', 'Bear call spread'), ('bear_put_spread', 'Bear put spread'), ('bull_put_spread', 'Bull put spread')], default='unspecified', max_length=100),
        ),
    ]
