# Generated by Django 3.1.2 on 2021-02-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0026_auto_20210206_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optioncontractsnapshot',
            name='premium',
        ),
    ]
