# Generated by Django 3.1.2 on 2021-02-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0027_remove_optioncontractsnapshot_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
