# Generated by Django 3.1.2 on 2021-02-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0028_subscription_paypal_plan_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('name', 'user')},
        ),
    ]
