# Generated by Django 3.1.2 on 2021-03-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0029_auto_20210225_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=250)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('week52_high', models.FloatField(blank=True, null=True)),
                ('week52_low', models.FloatField(blank=True, null=True)),
                ('week52_high_split_adjust_only', models.FloatField(blank=True, null=True)),
                ('week52_low_split_adjust_only', models.FloatField(blank=True, null=True)),
                ('shares_outstanding', models.FloatField(blank=True, null=True)),
                ('day200_moving_avg', models.FloatField(blank=True, null=True)),
                ('day50_moving_avg', models.FloatField(blank=True, null=True)),
                ('ttm_eps', models.FloatField(blank=True, null=True)),
                ('ttm_dividend_rate', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('next_dividend_date', models.DateField(blank=True, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('next_earnings_date', models.DateField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tiger.ticker')),
            ],
            options={
                'verbose_name_plural': 'Ticker stats',
            },
        ),
        migrations.CreateModel(
            name='ExpirationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiration_dates', to='tiger.ticker')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
