# Generated by Django 3.1.2 on 2021-03-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0030_expirationdate_tickerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerstats',
            name='dividend_payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerstats',
            name='split_declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerstats',
            name='split_ex_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
