# Generated by Django 3.1.2 on 2021-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0031_auto_20210303_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerstats',
            name='number_of_analysts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerstats',
            name='price_target_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerstats',
            name='price_target_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerstats',
            name='price_target_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
