# Generated by Django 3.1.2 on 2021-03-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0032_auto_20210305_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('holiday', 'Holiday')], default='holiday', max_length=20)),
            ],
            options={
                'unique_together': {('date', 'type')},
            },
        ),
    ]
