# Generated by Django 3.1.2 on 2021-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0034_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerstats',
            name='historical_volatility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
