# Generated by Django 3.1.2 on 2021-03-20 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0035_tickerstats_historical_volatility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('options_open_commission', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('options_close_commission', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_commission', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='brokers',
            field=models.ManyToManyField(to='tiger.Broker'),
        ),
    ]
