# Generated by Django 3.1.2 on 2021-03-20 18:58

from django.db import migrations


from django.db import migrations


brokers_json = [
    {
        'name': 'default',
        'options_open_commission': 0,
        'options_close_commission': 0,
        'is_default': True
    },
    {
        'name': 'Charles Schwab',
        'options_open_commission': 0.65,
        'options_close_commission': 0.65
    },
    {
        'name': 'Fidelity Investments',
        'options_open_commission': 0.65,
        'options_close_commission': 0.65
    },
    {
        'name': 'Robinhood',
        'options_open_commission': 0,
        'options_close_commission': 0
    },
    {
        'name': 'Ally Invest',
        'options_open_commission': 0.5,
        'options_close_commission': 0.5
    },
    {
        'name': 'TD Ameritrade',
        'options_open_commission': 0.65,
        'options_close_commission': 0.65
    },
    {
        'name': 'Merrill Edge',
        'options_open_commission': 0.65,
        'options_close_commission': 0.65
    },
]


def add_default_brokers(apps, schema_editor):
    Broker = apps.get_model('tiger', 'Broker')
    for broker_json in brokers_json:
        broker = Broker(**broker_json)
        broker.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0036_auto_20210320_1519'),
    ]

    operations = [
        migrations.RunPython(add_default_brokers)
    ]
