# Generated by Django 3.1.2 on 2021-03-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0037_auto_20210320_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerstats',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tiger.ticker'),
        ),
    ]
