# Generated by Django 3.1.2 on 2021-03-27 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0039_stocksnapshot_ticker_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled_strategies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
