# Generated by Django 3.1.2 on 2021-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0040_user_disabled_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
