# Generated by Django 3.1.2 on 2021-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0041_user_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerstats',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
