# Generated by Django 3.1.2 on 2021-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0042_auto_20210407_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('MANUAL', 'Manual')], default='PAYPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
