# Generated by Django 3.1.8 on 2021-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0043_auto_20210408_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesnapshot',
            name='type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('long_call', 'Long call'), ('covered_call', 'Covered call'), ('protective_put', 'Protective put'), ('long_put', 'Long put'), ('cash_secured_put', 'Cash secured put'), ('bull_call_spread', 'Bull call spread'), ('bear_call_spread', 'Bear call spread'), ('bear_put_spread', 'Bear put spread'), ('bull_put_spread', 'Bull put spread'), ('long_straddle', 'Long Straddle'), ('short_straddle', 'Short Straddle'), ('short_strangle', 'Short Strangle'), ('iron_butterfly', 'Iron Butterfly'), ('iron_condor', 'Iron Condor'), ('long_strangle', 'Long Strangle'), ('strap_straddle', 'Strap Straddle'), ('strap_strangle', 'Strap Strangle'), ('long_butterfly_spread', 'Long Butterfly Spread'), ('short_butterfly_spread', 'Short Butterfly Spread'), ('long_condor_spread', 'Long Condor Spread'), ('short_condor_spread', 'Short Condor Spread')], default='unspecified', max_length=100),
        ),
    ]
