# Generated by Django 3.1.8 on 2021-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0046_auto_20210531_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerstats',
            name='daily_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
