# Generated by Django 3.1.12 on 2021-06-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0047_tickerstats_daily_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerstats',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
